---
title: "BC Climate Extremes app"
author: "Aseem Sharma"
date: "`r paste('Date:', format(Sys.time(), '%d %B, %Y'))`"
output: html_document
editor_options: 
  chunk_output_type: console
---
## **Introduction**
### **Overview**

<a href='https://bcgov-env.shinyapps.io/bc_climate_extremes_app/'> bc_climate_extremes_app **(CEIapp)** </a>  is a R Shiny app that provides information on over 75 climate extreme indices (CEI) across Western North America, BC, and BC’s subregions (ecoprovinces, ecoregions, ecosections, watersheds, and municipalities) using <a href='https://www.gloh2o.org/mswx/'> Multi-Source Weather (MSWX) </a>  data for the period of 1979 to 2023 (as of August 2024). The app provides data and visualizations of annual and , if applicable, monthly climatology (average of 1981-2010), anomalies, and linear trends of the CEI for the selected region of interest. It offers options to  download all or part of the data, plots, and/or maps.

This is a product of the <a href ='https://www2.gov.bc.ca/gov/content/environment/natural-resource-stewardship/natural-resources-climate-change/future-forest-ecosystems-centre#:~:text=The%20Future%20Forest%20Ecosystems%20Centre%20(FFEC)%20was%20officially%20established%20in,on%20B.C.%27s%20forest%20ecosystems.'> Future Forest Ecosystems Center (FFEC)</a>. The FFEC is a scientific team that forecasts climate change impacts on B.C.'s forest ecosystems. The core role of the FFEC is to translate ecological knowledge into data, tools, and guidance to help ecosystem managers account for climate risks.

Please continue below to learn more about the CEI, the process and methods of indices calculations, key features of the app, and how this app can be useful. 
Navigate to the <a href='https://bcgov-env.shinyapps.io/bc_climate_extremes_app/'> Climate Extremes App  page </a> to access the data, plots, and maps. There are options to download plots and/or data. The <a href='https://bcgov-env.shinyapps.io/bc_climate_extremes_app/Feedback & Links page' >Feedback & Links page </a> contains a link to a form where users can provide comments and feedback related to the app. This page also includes links to other similar apps developed and maintained by the FFEC team.

### **Key Features**
- *Anomaly Calculation:* The app provides anomalies of CEI, highlighting deviations from historical norms.
- *Interactive Visualization:* It presents the data through intuitive maps, summary tables, and time series plots with trend magnitude and significance.
- *User-Friendly:* Accessible to both government employees and the general public, the app provides extreme indices for Western North America, BC, and its subregions (ecoprovinces, ecoregions, ecosections, watersheds, and Municipalities)
- *Wide Applicability:* Benefiting government employees, the broader scientific community, and interested individuals, it serves as a valuable resource for understanding BC's evolving extreme climate patterns.

## **Climate Extremes Indices (CEI)**
### **Background**

Changes in extreme weather profoundly impact ecosystems, ecological processes, and society making it crucial to understand how climate extremes change over space and time. Climate Extremes Indices (CEI) are statistical measures used to quantify and characterize extreme weather events related to temperature, precipitation, and other climate variables.CEI derived using daily data objectively extract information that has direct and more significant effect on natural systems and human beings; these indices help us understand the frequency, intensity, and duration of extreme conditions. The CEI condense complex, multidimensional climate data into a form that is easy to understand and useful for policy-making, decision-making, and research. These indices help us grasp how climate extremes defined mostly by temperature and precipitation, are changing over time across different locations. For instance, understanding whether there is an increase or decrease in the number of frost days or the length of the growing season can inform agricultural decisions.

We use the <a href = 'https://climpact-sci.org/'> Climpact R software package </a> to calculate CEI. Using Climpact we calculate the core 27 CEI also called Expert Team on Climate Change Detection and Indices <a href ='https://etccdi.pacificclimate.org/indices.shtml'> (ETCCDI) </a> indices <a href = ' https://doi.org/10.1002/wcc.147'> (Zhang et al., 2011) </a> , along with sectoral indices, also called Expert Team on Sector-Specific Climate Indices <a href ='https://climpact-sci.org/about/project/'> (ET-SCI) </a>. The ET-SCI includes indices that have sectoral applications such as no of heatwaves <a href = 'https://doi.org/10.1175/JCLI-D-12-00383.1'> (Perkins & Alexander, 2013) </a> or the SPEI values <a href = 'https://doi.org/10.1175/2009JCLI2909.1'> (Vicente-Serrano et al., 2010) </a> for a given year and/or month. In total, we calculated 79 different CEI. The table at the bottom of the page presents the name, definition and description of the indices along with their timescale. Please refer to the <a href ='https://github.com/ARCCSS-extremes/climpact/blob/master/www/user_guide/Climpact_user_guide.md'>  climpact package documentation page </a> and references there for further details on each of these indices. 

We used daily minimum and maximum temperature and precipitation data from MSWX daily data to calculate the CEI for the period of 1979-2023. The MSWX data is based on ERA5 data and is bias corrected and downscaled using high-resolution reference climatologies. It is ~9 km × ~9 km spatial resolution daily data that merges gauge, satellite, and reanalysis data to obtain the highest quality precipitation estimates. Please refer to <a href = 'https://www.gloh2o.org/mswx/'>  MSWX data site </a> and <a href = 'https://doi.org/10.1175/BAMS-D-21-0145.1'> paper </a> or more information on the data.<a href = 'https://services.pacificclimate.org/pcex/app/#/data/climo/ce_cmip6_mbcn'> Pacific Climate Impacts Consortium (PCIC) </a> and <a href = 'https://climate-scenarios.canada.ca/?page=CanDCS6-indices'> Government of Canada </a> also provide some of the CEI for Canada using different model output. However, this app

- has more CEI including sectoral indices such as heatwaves, cold waves, and SPEI
- provides CEI for any of chosen regions from Western North America, BC, ecoprovinces of BC, ecoregions of BC, ecosections of BC, watersheds of BC, and Municipalities of BC
- provides indices in both annual and monthly basis ( where applicable)
- provides spatial changes and long-term trends of CEI, get summary and data at once
- uses high-quality high resolution reanalysis datasets that combines both stations data and forecast model output

### **Name and definition of the Climate Extreme Indices (CEI)**





